FEM-2594 netkit network calls retry
kaltura/netkit-android pull request #17
Opened 2019-08-21 18:14 UTC by giladna

2019-08-21 21:02 UTC, noamtamim requested changes

2019-08-21 21:02 UTC, noamtamim commented on netkit/src/main/java/com/kaltura/netkit/utils/NetworkEventListener.java
> +public interface NetworkEventListener {
Rename to NetworkErrorListener.

2019-08-25 15:21 UTC, noamtamim approved these changes

2019-08-25 20:10 UTC, OrenMe approved these changes

2019-08-26 06:01 UTC, merged